server:
  port: 8081
spring:
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 500000KB
      max-file-size: 500000KB
springdoc:
  swagger-ui:
    path: /swagger-ui.html